### ISSUE TITLE
ping_tun_tap example not working: Write to object stream_in_startofpacket was scheduled during a read-only sync phase.

### ISSUE THREAD

**Issue by stefan-muc** [potentialventures/cocotb#662]
Hey, I'm new to cocotb and wanted to try the ping_tun_tap example, but I can't get it to work on Xubuntu Linux 18.04, despites I follow the [Tutorial](https://cocotb.readthedocs.io/en/latest/ping_tun_tap.html).

Depending on the changeset I get different errors:
c1e259c (release version 1.0):

    GpiCommon.cpp:136:21: error: invalid suffix on literal; C++11 requires a space between literal and string macro [-Werror=literal-suffix]
     #define DOT_LIB_EXT "."xstr(LIB_EXT)

312e000 (Fix C++11 error message):

    gpivpi:`/home/cdev/work/cocotb/build/libs/x86_64/gpivpi.vpl' failed to open using dlopen() because:
        /home/cdev/work/cocotb/build/libs/x86_64/libcocotbutils.so: undefined symbol: context.
    VCD info: dumpfile waveform.vcd opened for output.
    Sim running...

Without much output. A waveform.vcd is generated but it only contains one data point (905 bytes of size)

f76e4fc (Merge pull request #565 from chiggs/pending) introduces a new output format which shows an error:

    Send raised exception: Write to object stream_in_startofpacket was scheduled during a read-only sync phase.
     File "/home/decorators.py", line 120, in send
       return self._coro.send(value)
     File "/home/drivers/avalon.py", line 575, in _send_string
       self.bus.startofpacket <= 0
     File "/home/handle.py", line 419, in __le__
       self.value = value
     File "/home/handle.py", line 144, in __setattr__
       return object.__setattr__(self, name, value)
     File "/home/handle.py", line 435, in <lambda>
       fset=lambda self,v: self._setcachedvalue(v),
     File "/home/handle.py", line 642, in _setcachedvalue
       cocotb.scheduler.save_write(self, value)
     File "/home/scheduler.py", line 461, in save_write
       raise Exception("Write to object {0} was scheduled during a read-only sync phase.".format(handle._name))
    

Which stays quite the same until current master changeset (dce481a), just some line numbers change marginally.

So is this example supposed to be functional?
The tests at `cocotb/examples/endian_swapper/tests` run successfully, so I guess my environment should be okay.
