### ISSUE TITLE
Implicit declaration of function 

### ISSUE THREAD

**Issue by andresdemski** [potentialventures/cocotb#973]
Current master branch (578293e17509410c0024356f431d03009032c813) is broken.

```console
$ make clean && make
....
gcc -Werror -Wcast-qual -Wcast-align -Wwrite-strings -Wall -Wno-unused-parameter -fno-common -g -DDEBUG -fpic -DICARUS -Wstrict-prototypes -Waggregate-return -DICARUS -c -I/home/ademski/Documents/satellogic/hdlteam/cocotb/cocotb/share/include -I/usr/include/python3.7m  -o /home/ademski/Documents/satellogic/hdlteam/common-cores/test/fifo_sbi_tb/build/obj/x86_64/cocotb_utils.o cocotb_utils.c
cocotb_utils.c: In function ‘to_python’:
cocotb_utils.c:45:9: error: implicit declaration of function ‘exit’ [-Werror=implicit-function-declaration]
         exit(1);
         ^~~~
cocotb_utils.c:45:9: error: incompatible implicit declaration of built-in function ‘exit’ [-Werror]
cocotb_utils.c:45:9: note: include ‘<stdlib.h>’ or provide a declaration of ‘exit’
cocotb_utils.c:35:1:
+#include <stdlib.h>
 #else
cocotb_utils.c:45:9:
         exit(1);
         ^~~~
cocotb_utils.c: In function ‘to_simulator’:
cocotb_utils.c:54:9: error: incompatible implicit declaration of built-in function ‘exit’ [-Werror]
         exit(1);
         ^~~~
cocotb_utils.c:54:9: note: include ‘<stdlib.h>’ or provide a declaration of ‘exit’
cc1: all warnings being treated as errors
```

**Comment by eric-wieser** [comment]
Introduced in #954, looks like it was merged without CI passing

**Comment by imphil** [comment]
That was my fault, we recently had half-failing tests and I didn't double-check that the symptom is the same. It's now reverted.
